"""Constants for the Anker Solix X1 integration."""

from __future__ import annotations

from homeassistant.const import Platform

DOMAIN = "anker_solix_x1"

CONF_SCAN_INTERVAL = "scan_interval"

DEFAULT_NAME = "Anker Solix X1"
DEFAULT_PORT = 502
DEFAULT_SCAN_INTERVAL = 5
DEFAULT_UNIT_ID = 1
# X1 addresses in the protocol table appear to be usable directly (0-based).
# Set to -1 only if your device documentation uses 1-based addressing.
MODBUS_ADDRESS_OFFSET = 0

PLATFORMS: list[Platform] = [Platform.SENSOR]

# Sensors can be extended by adding entries to this list.
# - address: protocol address (1-based, as in documentation)
# - count: number of 16-bit Modbus registers
# - data_type: uint16 | int16 | uint32 | int32 | string
# - gain: value divisor from protocol table (10 => raw/10)
# - swap: "word" | "byte" | "word_byte" | None
SENSOR_DEFINITIONS: list[dict[str, str | int | float | None]] = [
    {
        "key": "model_name",
        "name": "Modellname",
        "address": 10090,
        "count": 10,
        "data_type": "string",
        "swap": "byte",
        "gain": 1,
        "unit": None,
        "device_class": None,
        "state_class": None,
        "entity_category": "diagnostic",
    },
    {
        "key": "serial_number",
        "name": "Seriennummer",
        "address": 10100,
        "count": 12,
        "data_type": "string",
        "swap": "byte",
        "gain": 1,
        "unit": None,
        "device_class": None,
        "state_class": None,
        "entity_category": "diagnostic",
    },
    {
        "key": "software_version",
        "name": "Software Version",
        "address": 10112,
        "count": 6,
        "data_type": "string",
        "swap": "byte",
        "gain": 1,
        "unit": None,
        "device_class": None,
        "state_class": None,
        "entity_category": "diagnostic",
    },
    {
        "key": "grid_frequency",
        "name": "Netzfrequenz",
        "address": 10213,
        "count": 1,
        "data_type": "uint16",
        "gain": 100,
        "unit": "Hz",
        "device_class": "frequency",
        "state_class": "measurement",
    },
    {
        "key": "pv_power",
        "name": "PV Leistung",
        "address": 10002,
        "count": 2,
        "data_type": "int32",
        "swap": "word",
        "gain": 1,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
    },
    {
        "key": "active_power_pcs_ac_side",
        "name": "Haus Verbrauch",
        "address": 10006,
        "count": 2,
        "data_type": "int32",
        "swap": "word",
        "gain": 1,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
    },
    {
        "key": "battery_power_pcs",
        "name": "Akku Leistung",
        "address": 10008,
        "count": 2,
        "data_type": "int32",
        "swap": "word",
        "gain": 1,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
    },
    {
        "key": "load_power",
        "name": "Power Load",
        "address": 10010,
        "count": 2,
        "data_type": "int32",
        "swap": "word",
        "gain": 1,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
    },
    {
        "key": "grid_power",
        "name": "Power Grid",
        "address": 10012,
        "count": 2,
        "data_type": "int32",
        "swap": "word",
        "gain": 1,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
    },
    {
        "key": "pv1_voltage",
        "name": "PV1 Spannung",
        "address": 10167,
        "count": 1,
        "data_type": "uint16",
        "gain": 10,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
    },
    {
        "key": "pv1_current",
        "name": "PV1 Strom",
        "address": 10168,
        "count": 1,
        "data_type": "uint16",
        "gain": 100,
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
    },
    {
        "key": "pv2_voltage",
        "name": "PV2 Spannung",
        "address": 10169,
        "count": 1,
        "data_type": "uint16",
        "gain": 10,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
    },
    {
        "key": "pv2_current",
        "name": "PV2 Strom",
        "address": 10170,
        "count": 1,
        "data_type": "uint16",
        "gain": 100,
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
    },
    {
        "key": "phase_a_voltage",
        "name": "Spannung Phase A",
        "address": 10202,
        "count": 1,
        "data_type": "uint16",
        "gain": 10,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
    },
    {
        "key": "phase_b_voltage",
        "name": "Spannung Phase B",
        "address": 10203,
        "count": 1,
        "data_type": "uint16",
        "gain": 10,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
    },
    {
        "key": "phase_c_voltage",
        "name": "Spannung Phase C",
        "address": 10204,
        "count": 1,
        "data_type": "uint16",
        "gain": 10,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
    },
    {
        "key": "phase_a_current",
        "name": "Strom Phase A",
        "address": 10205,
        "count": 1,
        "data_type": "uint16",
        "gain": 100,
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
    },
    {
        "key": "phase_b_current",
        "name": "Strom Phase B",
        "address": 10206,
        "count": 1,
        "data_type": "int16",
        "gain": 100,
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
    },
    {
        "key": "phase_c_current",
        "name": "Strom Phase C",
        "address": 10207,
        "count": 1,
        "data_type": "int16",
        "gain": 100,
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
    },
    {
        "key": "backup_or_phase_a_current",
        "name": "Backup/Phase A Strom",
        "address": 10230,
        "count": 1,
        "data_type": "uint16",
        "gain": 100,
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
    },
    {
        "key": "backup_phase_b_current",
        "name": "Backup Phase B Strom",
        "address": 10231,
        "count": 1,
        "data_type": "int16",
        "gain": 100,
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
    },
    {
        "key": "backup_phase_c_current",
        "name": "Backup Phase C Strom",
        "address": 10232,
        "count": 1,
        "data_type": "int16",
        "gain": 100,
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
    },
    {
        "key": "inverter_temperature",
        "name": "Temperatur",
        "address": 10156,
        "count": 1,
        "data_type": "int16",
        "gain": 10,
        "unit": "°C",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    # Akku Uebersicht (systemweit, nicht Akku1..Akku6 einzeln)
    {
        "key": "akku_health",
        "name": "Akku Gesundheit",
        "address": 10015,
        "count": 1,
        "data_type": "uint16",
        "gain": 1,
        "unit": "%",
        "device_class": "battery",
        "state_class": "measurement",
    },
    {
        "key": "akku_number_of_packs",
        "name": "Akku Anzahl Packs",
        "address": 10249,
        "count": 1,
        "data_type": "uint16",
        "gain": 1,
        "unit": None,
        "device_class": None,
        "state_class": "measurement",
    },
    {
        "key": "akku_rated_capacity",
        "name": "Akku Nennkapazitaet",
        "address": 10250,
        "count": 2,
        "data_type": "uint32",
        "gain": 10,
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "measurement",
    },
    {
        "key": "akku_status",
        "name": "Akku Status",
        "address": 10252,
        "count": 1,
        "data_type": "uint16",
        "gain": 1,
        "unit": None,
        "device_class": None,
        "state_class": "measurement",
    },
    {
        "key": "akku_voltage",
        "name": "Akku Spannung",
        "address": 10253,
        "count": 1,
        "data_type": "uint16",
        "gain": 10,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
    },
    {
        "key": "akku_soc",
        "name": "Akku SoC",
        "address": 10256,
        "count": 1,
        "data_type": "uint16",
        "gain": 1,
        "unit": "%",
        "device_class": "battery",
        "state_class": "measurement",
    },
    {
        "key": "akku_soh",
        "name": "Akku SoH",
        "address": 10257,
        "count": 1,
        "data_type": "uint16",
        "gain": 1,
        "unit": "%",
        "device_class": None,
        "state_class": "measurement",
    },
    {
        "key": "akku_daily_charge_energy",
        "name": "Akku Tages-Ladeenergie",
        "address": 10258,
        "count": 2,
        "data_type": "uint32",
        "swap": "word",
        "gain": 10,
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
    },
    {
        "key": "akku_daily_discharge_energy",
        "name": "Akku Tages-Entladeenergie",
        "address": 10260,
        "count": 2,
        "data_type": "uint32",
        "swap": "word",
        "gain": 10,
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
    },
    {
        "key": "akku_total_charge_energy",
        "name": "Akku Gesamt-Ladeenergie",
        "address": 10262,
        "count": 2,
        "data_type": "uint32",
        "swap": "word",
        "gain": 100,
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
    },
    {
        "key": "akku_total_discharge_energy",
        "name": "Akku Gesamt-Entladeenergie",
        "address": 10264,
        "count": 2,
        "data_type": "uint32",
        "swap": "word",
        "gain": 100,
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
    },
    # Akku1 Block (einzelner Pack; Akku gesamt ist in der Akku-Uebersicht)
    {
        "key": "akku1_model_name",
        "name": "Akku1 Modellname",
        "address": 10284,
        "count": 10,
        "data_type": "string",
        "swap": "byte",
        "gain": 1,
        "unit": None,
        "device_class": None,
        "state_class": None,
        "entity_category": "diagnostic",
    },
    {
        "key": "akku1_serial_number",
        "name": "Akku1 Seriennummer",
        "address": 10294,
        "count": 12,
        "data_type": "string",
        "swap": "byte",
        "gain": 1,
        "unit": None,
        "device_class": None,
        "state_class": None,
        "entity_category": "diagnostic",
    },
    {
        "key": "akku1_software_version",
        "name": "Akku1 Software Version",
        "address": 10306,
        "count": 6,
        "data_type": "string",
        "swap": "byte",
        "gain": 1,
        "unit": None,
        "device_class": None,
        "state_class": None,
        "entity_category": "diagnostic",
    },
    {
        "key": "akku1_hardware_version",
        "name": "Akku1 Hardware Version",
        "address": 10312,
        "count": 6,
        "data_type": "string",
        "swap": "byte",
        "gain": 1,
        "unit": None,
        "device_class": None,
        "state_class": None,
        "entity_category": "diagnostic",
    },
    {
        "key": "akku1_rate_capacity",
        "name": "Akku1 Rate Capacity",
        "address": 10318,
        "count": 2,
        "data_type": "uint32",
        "swap": "word",
        "gain": 100,
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "measurement",
    },
    {
        "key": "akku1_status",
        "name": "Akku1 Status",
        "address": 10320,
        "count": 1,
        "data_type": "uint16",
        "gain": 1,
        "unit": None,
        "device_class": None,
        "state_class": "measurement",
    },
    {
        "key": "akku1_voltage",
        "name": "Akku1 Spannung",
        "address": 10321,
        "count": 1,
        "data_type": "uint16",
        "gain": 10,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
    },
    {
        "key": "akku1_power",
        "name": "Akku1 Leistung",
        "address": 10322,
        "count": 2,
        "data_type": "int32",
        "swap": "word",
        "gain": 1,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
    },
    {
        "key": "akku1_soc",
        "name": "Akku1 SoC",
        "address": 10324,
        "count": 1,
        "data_type": "uint16",
        "gain": 1,
        "unit": "%",
        "device_class": "battery",
        "state_class": "measurement",
    },
    {
        "key": "akku1_soh",
        "name": "Akku1 SoH",
        "address": 10325,
        "count": 1,
        "data_type": "uint16",
        "gain": 1,
        "unit": "%",
        "device_class": None,
        "state_class": "measurement",
    },
    {
        "key": "akku1_total_discharge_energy",
        "name": "Akku1 Gesamt-Entladeenergie",
        "address": 10326,
        "count": 2,
        "data_type": "uint32",
        "swap": "word",
        "gain": 100,
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
    },
    {
        "key": "akku1_maximum_temperature",
        "name": "Akku1 Max Temperatur",
        "address": 10328,
        "count": 1,
        "data_type": "uint16",
        "gain": 1,
        "unit": "°C",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    {
        "key": "akku1_minimum_temperature",
        "name": "Akku1 Min Temperatur",
        "address": 10329,
        "count": 1,
        "data_type": "uint16",
        "gain": 1,
        "unit": "°C",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    {
        "key": "daily_pv_generation",
        "name": "Tages-PV-Erzeugung",
        "address": 10016,
        "count": 2,
        "data_type": "uint32",
        "swap": "word",
        "gain": 100,
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
    },
    {
        "key": "total_pv_generation",
        "name": "Gesamt-PV-Erzeugung",
        "address": 10018,
        "count": 2,
        "data_type": "uint32",
        "swap": "word",
        "gain": 100,
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
    },
    {
        "key": "daily_battery_charge_energy",
        "name": "Tages-Batterie-Ladeenergie",
        "address": 10020,
        "count": 2,
        "data_type": "uint32",
        "swap": "word",
        "gain": 100,
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
    },
    {
        "key": "daily_load_consumption_energy",
        "name": "Tages-Lastverbrauch",
        "address": 10024,
        "count": 2,
        "data_type": "uint32",
        "swap": "word",
        "gain": 100,
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
    },
    {
        "key": "total_load_consumption_energy",
        "name": "Gesamt-Lastverbrauch",
        "address": 10026,
        "count": 2,
        "data_type": "uint32",
        "swap": "word",
        "gain": 100,
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
    },
    {
        "key": "daily_purchased_energy",
        "name": "Tages-Netzbezug",
        "address": 10028,
        "count": 2,
        "data_type": "uint32",
        "swap": "word",
        "gain": 100,
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
    },
    {
        "key": "total_purchased_energy",
        "name": "Gesamt-Netzbezug",
        "address": 10030,
        "count": 2,
        "data_type": "uint32",
        "swap": "word",
        "gain": 100,
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
    },
    {
        "key": "daily_feed_in_energy",
        "name": "Tages-Einspeisung",
        "address": 10032,
        "count": 2,
        "data_type": "uint32",
        "swap": "word",
        "gain": 100,
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
    },
    {
        "key": "total_feed_in_energy",
        "name": "Gesamt-Einspeisung",
        "address": 10034,
        "count": 2,
        "data_type": "uint32",
        "swap": "word",
        "gain": 100,
        "unit": "kWh",
        "device_class": "energy",
        "state_class": "total_increasing",
    },
]

